include: package:lint/strict.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false
    avoid_classes_with_only_static_members: false
