name: w_sharme_beauty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.16.1
  dartx: ^1.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_gen_runner: ^5.4.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  go_router: ^13.2.2
  image_picker: ^1.1.0
  injectable: ^2.4.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  pinput: ^4.0.0
  shimmer: ^3.0.0
  uuid: ^4.4.0


dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.4.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/
  fonts:
    - family: GTEastiProDisplay
      fonts:
        - asset: assets/fonts/GT Eesti Pro Display Regular.otf

flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true

